import type { Portal } from "./schema";

export const portals: Portal[] = [
  {
    id: "linkedin",
    name: "LinkedIn",
    url: "https://www.linkedin.com/jobs/",
    description: "Professional network and job search",
    category: "general",
  },
  {
    id: "naukri",
    name: "Naukri",
    url: "https://www.naukri.com/",
    description: "India's largest job portal",
    category: "general",
  },
  {
    id: "indeed",
    name: "Indeed",
    url: "https://www.indeed.com/",
    description: "Global job search engine",
    category: "general",
  },
  {
    id: "monster",
    name: "Monster",
    url: "https://www.monsterindia.com/",
    description: "Job search and career advice",
    category: "general",
  },
  {
    id: "shine",
    name: "Shine",
    url: "https://www.shine.com/",
    description: "Job search across industries in India",
    category: "general",
  },
  {
    id: "instahyre",
    name: "Instahyre",
    url: "https://www.instahyre.com/",
    description: "Curated tech job matches",
    category: "tech",
  },
  {
    id: "hirist",
    name: "Hirist",
    url: "https://www.hirist.com/",
    description: "Tech-focused job portal",
    category: "tech",
  },
  {
    id: "cutshort",
    name: "Cutshort",
    url: "https://cutshort.io/",
    description: "Startup and tech hiring platform",
    category: "tech",
  },
  {
    id: "iimjobs",
    name: "iimjobs",
    url: "https://www.iimjobs.com/",
    description: "Senior and management-level jobs",
    category: "tech",
  },
  {
    id: "wellfound",
    name: "Wellfound",
    url: "https://wellfound.com/",
    description: "Startup jobs, formerly AngelList Talent",
    category: "tech",
  },
  {
    id: "weworkremotely",
    name: "We Work Remotely",
    url: "https://weworkremotely.com/",
    description: "Largest remote work community",
    category: "remote",
  },
  {
    id: "remoteok",
    name: "RemoteOK",
    url: "https://remoteok.com/",
    description: "Remote jobs across every field",
    category: "remote",
  },
  {
    id: "toptal",
    name: "Toptal",
    url: "https://www.toptal.com/",
    description: "Freelance network for top talent",
    category: "remote",
  },
  {
    id: "turing",
    name: "Turing",
    url: "https://www.turing.com/",
    description: "Remote software jobs at US companies",
    category: "remote",
  },
  {
    id: "glassdoor",
    name: "Glassdoor",
    url: "https://www.glassdoor.com/",
    description: "Company reviews, salaries, and interviews",
    category: "research",
  },
  {
    id: "ambitionbox",
    name: "AmbitionBox",
    url: "https://www.ambitionbox.com/",
    description: "Company reviews and salary insights",
    category: "research",
  },
  {
    id: "levelsfyi",
    name: "Levels.fyi",
    url: "https://www.levels.fyi/",
    description: "Tech compensation benchmarking",
    category: "research",
  },
  {
    id: "hrapp",
    name: "HRapp Careers",
    url: "https://hrapp.resul.team/#/careers",
    description: "Careers page powered by the HRapp ATS",
    category: "general",
  },
  {
    id: "greenhouse",
    name: "Greenhouse",
    url: "https://my.greenhouse.io/dashboard",
    description: "Applicant tracking and hiring platform",
    category: "general",
  },
  {
    id: "internshala",
    name: "Internshala",
    url: "https://internshala.com/jobs/matching-preferences/",
    description: "Internships and entry-level jobs in India",
    category: "general",
  },
  {
    id: "hirist-tech",
    name: "Hirist Jobfeed",
    url: "https://www.hirist.tech/jobfeed",
    description: "Curated tech job feed",
    category: "tech",
  },
  {
    id: "digicert",
    name: "DigiCert Careers",
    url: "https://www.digicert.com/careers",
    description: "Careers at DigiCert",
    category: "general",
  },
  {
    id: "simplyhired-in",
    name: "SimplyHired India",
    url: "https://www.simplyhired.co.in/",
    description: "Job search engine for India",
    category: "general",
  },
  {
    id: "welcometothejungle",
    name: "Welcome to the Jungle",
    url: "https://www.welcometothejungle.com/en/jobs",
    description: "Company culture-focused job platform",
    category: "general",
  },
  {
    id: "workopolis",
    name: "Workopolis",
    url: "https://www.workopolis.com/",
    description: "Canadian job search site",
    category: "general",
  },
  {
    id: "careerbuilder",
    name: "CareerBuilder",
    url: "https://www.careerbuilder.com/",
    description: "Job search and recruiting platform",
    category: "general",
  },
  {
    id: "myjobhunter",
    name: "MyJobHunter.ai",
    url: "https://www.myjobhunter.ai/",
    description: "AI-powered job matching",
    category: "general",
  },
  {
    id: "upwork",
    name: "Upwork",
    url: "https://www.upwork.com/",
    description: "Freelance and contract work marketplace",
    category: "remote",
  },
  {
    id: "jobboom",
    name: "Jobboom",
    url: "https://www.jobboom.com/en",
    description: "Canadian job search portal",
    category: "general",
  },
  {
    id: "hiringcafe",
    name: "Hiring Cafe",
    url: "https://hiringcafe.com/",
    description: "Aggregated job search across company career sites",
    category: "general",
  },
];
