import type { Portal } from "./schema";

export const portals: Portal[] = [
  {
    id: "linkedin",
    name: "LinkedIn",
    url: "https://www.linkedin.com/jobs/",
    description: "Professional network and job search",
    category: "general",
  },
  {
    id: "naukri",
    name: "Naukri",
    url: "https://www.naukri.com/",
    description: "India's largest job portal",
    category: "general",
  },
  {
    id: "indeed",
    name: "Indeed",
    url: "https://www.indeed.com/",
    description: "Global job search engine",
    category: "general",
  },
  {
    id: "monster",
    name: "Monster",
    url: "https://www.monsterindia.com/",
    description: "Job search and career advice",
    category: "general",
  },
  {
    id: "shine",
    name: "Shine",
    url: "https://www.shine.com/",
    description: "Job search across industries in India",
    category: "general",
  },
  {
    id: "instahyre",
    name: "Instahyre",
    url: "https://www.instahyre.com/",
    description: "Curated tech job matches",
    category: "tech",
  },
  {
    id: "hirist",
    name: "Hirist",
    url: "https://www.hirist.com/",
    description: "Tech-focused job portal",
    category: "tech",
  },
  {
    id: "cutshort",
    name: "Cutshort",
    url: "https://cutshort.io/",
    description: "Startup and tech hiring platform",
    category: "tech",
  },
  {
    id: "iimjobs",
    name: "iimjobs",
    url: "https://www.iimjobs.com/",
    description: "Senior and management-level jobs",
    category: "tech",
  },
  {
    id: "wellfound",
    name: "Wellfound",
    url: "https://wellfound.com/",
    description: "Startup jobs, formerly AngelList Talent",
    category: "tech",
  },
  {
    id: "weworkremotely",
    name: "We Work Remotely",
    url: "https://weworkremotely.com/",
    description: "Largest remote work community",
    category: "remote",
  },
  {
    id: "remoteok",
    name: "RemoteOK",
    url: "https://remoteok.com/",
    description: "Remote jobs across every field",
    category: "remote",
  },
  {
    id: "toptal",
    name: "Toptal",
    url: "https://www.toptal.com/",
    description: "Freelance network for top talent",
    category: "remote",
  },
  {
    id: "turing",
    name: "Turing",
    url: "https://www.turing.com/",
    description: "Remote software jobs at US companies",
    category: "remote",
  },
  {
    id: "glassdoor",
    name: "Glassdoor",
    url: "https://www.glassdoor.com/",
    description: "Company reviews, salaries, and interviews",
    category: "research",
  },
  {
    id: "ambitionbox",
    name: "AmbitionBox",
    url: "https://www.ambitionbox.com/",
    description: "Company reviews and salary insights",
    category: "research",
  },
  {
    id: "levelsfyi",
    name: "Levels.fyi",
    url: "https://www.levels.fyi/",
    description: "Tech compensation benchmarking",
    category: "research",
  },
];
